name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Restore dependencies TheUKTories.DataStores
      working-directory: TheUKTories.DataStores/
      run: dotnet restore
    - name: Build TheUKTories.DataStores
      working-directory: TheUKTories.DataStores/
      run: dotnet build --no-restore
    - name: Restore dependencies TheUKTories
      working-directory: TheUKTories/
      run: dotnet restore
    - name: Build TheUKTories
      working-directory: TheUKTories/
      run: dotnet build --no-restore
